### ISSUE TITLE
layoutname() and scriptname() returning error

### ISSUE THREAD

**Issue by connorblack** [geistinteractive/fms-js#6]
Hey, I have a quick problem I'm consistently running into and I was hoping you could help me out. 

So I'm able to successfully connect and get all of my database names (names starred out for privacy):

```
[ { DATABASE_NAME: '****', modid: '0', recid: '0' },
  { DATABASE_NAME: '****', modid: '0', recid: '0' },
  { DATABASE_NAME: '****', modid: '0', recid: '0' },
  ...]
```

But when I take a value of `DATABASE_NAME` and use it like so:
```
connection.db('****')
      .scriptnames()
      .send(console.log)
```
or 
```
connection.db('****')
      .layoutnames()
      .send(console.log)
```
I don't get the expected response, but instead this error:
```
{ [Error: Unexpected close tag
Line: 0
Column: 1047
Char: >] response: undefined }
double callback!
```

Can you point me in the right direction? The code/examples are simple so I'm pretty sure I'm implementing them correctly, but I have no idea why the database listing would work but the layout/scripts listing won't.

For reference, I'm running filemaker server 14. 

Thanks.

**Comment by jrhall** [comment]
I could be way off but maybe this will help!

Do you have a ">" in at least one script name and in at least one layout name? It looks like the error that you're getting is from an XML parsing library that is like a sub-sub-sub dependency of fms-js (https://github.com/isaacs/sax-js/blob/9f9814f544f1c5b89dd1d79957c041f37e845b4a/lib/sax.js#L887). If that's the case, maybe the XML parser is getting tripped up on the ">"? You could try renaming your scripts/ layouts to remove characters that need to be escaped in XML. If many of your scripts/layouts need to be changed and you want an easier way to test, maybe try creating a test database that has no special characters in the layout/ script names and see if you can get fms-js to work there.

Hope that helps! I'd be curious to know how it turns out.

**Comment by jrhall** [comment]
Hmm, scratch that, I'm sure that I have angle brackets in some of my scriptnames. Sorry!

**Comment by toddgeist** [comment]
Hello,

Are you able to get any other queries to work?  Is the issue just with scriptnames and layoutnames?

I am pretty sure that I have seen this before when the WPE stops working.  We should be catching this case but it is hard to reproduce as it is random.  But try restarting the WPE.

**Comment by connorblack** [comment]
@toddgeist restarting the WPE fixed it - thanks!
